org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRclass=true
kotlin.code.style=official
kotlin.compiler.execution.strategy=in-process
kotlin.daemon.useFallbackStrategy=true

# Default base URL for real-device testing on the same Wi‑Fi network
BASE_URL=http://192.168.0.26:8000/api/


